FROM python:3.12.0-bookworm
ENV APP /app
RUN mkdir $APP
WORKDIR $APP
EXPOSE 5000
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY . .
#CMD [ "uwsgi", "--ini", "app.ini" ]
CMD [ "gunicorn", "-w", "3", "-b", "0.0.0.0:8081","run" ]